---
title: "eMLR model loop"
author: "Donghe Zhu and Dr Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r library, message = FALSE, warning = FALSE}
library(tidyverse)
library(patchwork)
library(stars)
library(collapse)
library(lubridate)
```

```{r read_parameters, include = FALSE}
parameters <-
  read_rds(here::here("data",
                       "parameters.rds"))
```

```{r read_mask_files, include = FALSE}

basinmask <- read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "basin_mask_WOA18_AIP.csv"
  )
)
basinmask <- basinmask %>%
  select(-basin)

landmask <-  read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "land_mask_WOA18.csv"
  )
)

```

```{r read_section_global_coordinates, include = FALSE}

section_global_coordinates <- read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "section_global_coordinates.csv"
  )
)

```

```{r read_functions, include = FALSE}
source(here::here("code", "plotting_functions.R"))
```

```{r ggplot_theme, include = FALSE}
# ggplot theme for all plots
theme_set(theme_bw())
```


# Read GLODAP clean data

```{r read_GLODAP_clean_data}

GLODAP <- read_csv(here::here("data",
                       "GLODAPv2.2020_Merged_clean.csv"))

```


# Subset model data according to GLODAP observation since 1982

## Regridded variable forcing model data

```{r subset_regridded_variable_forcing_data}

# set path to model output files
path_model_regridded <-
  "/net/kryo/work/loher/CESM_output/RECCAP2/regridded/"

# set name of modelled to be subsetted
model_ID <- "GIAF_JRA_2020"

# for loop across years
#years <- c("1982":"2019")
years <- c("1982":"1983")

for (i_year in years) {
  
  # Uncomment line below for manual testing
  #i_year <- years[1]
  
  # select GLODAP data for that year
  GLODAP_year <- GLODAP %>%
    filter(year == i_year)
  
  # for loop across variables
  #variables <- c("DIC", "ALK", "O2", "NO3", "PO4", "SiO3", "SALT", "TEMP")
  variables <- c("DIC", "ALK")
  
  for (i_variable in variables) {
    
    # Uncomment line below for manual testing
    #i_variable <- variables[1]

    # read list of all files
    file <-
      list.files(path = path_model_regridded,
                 pattern = paste(model_ID,"_", i_variable, "_", i_year, ".nc", sep = ""))
    print(file)

    # read in data
    variable_data <-
      read_ncdf(paste(path_model_regridded,
                      file,
                      sep = ""))
    
    # convert to tibble
    variable_data_tibble <- variable_data %>%
      as_tibble()
    
    # remove open link to nc file
    rm(variable_data)
    
    # remove na values -> do this early, to speed up subsequent tasks
    variable_data_tibble <-
      variable_data_tibble %>%
      filter(!is.na(!!sym(i_variable)))

    # convert longitudes
    variable_data_tibble <- variable_data_tibble %>%
      mutate(lon = if_else(lon < 20, lon + 360, lon))
    
    # mutate variables and filter NaN value
    variable_data_tibble <- variable_data_tibble %>%
      rename(depth = z_t) %>%
      mutate(depth = depth / 100,
             month = month(time),
             !!sym(i_variable) := as.numeric(!!sym(i_variable))) %>%
      select(-time)
    
    # create month x lat x lon grid of observations
    grid_subset <- GLODAP_year %>%
      select(month, lat, lon) %>%
      unique()

    # subset model at month x lat x lon grid of observations
    model_subset <-
      inner_join(grid_subset, variable_data_tibble)
    
    # create month x lat x lon x depth grid of observations
    obs_depth <- GLODAP_year %>%
      select(month, lat, lon, depth) %>%
      unique()
    
    # join model and month x lat x lon x depth grid of observations
    model_obs <- full_join(model_subset, obs_depth)
    
    # calculate nr of observations per month x lat x lon grid
    model_obs <- model_obs %>%
      group_by(month, lat, lon) %>%
      mutate(n = sum(!is.na(!!sym(i_variable)))) %>%
      ungroup()

    # interpolate variable value from model to observation depth
    model_obs_interpo <- model_obs %>%
      filter(n > 1) %>%
      group_by(lon, lat, month) %>%
      arrange(depth) %>%
      mutate(!!sym(i_variable) := approxfun(depth, !!sym(i_variable), rule = 2)(depth)) %>%
      ungroup()
    
    # subsetted interpolated values at observation depth
    model_obs_interpo <- inner_join(obs_depth, model_obs_interpo) %>%
      select(-n) %>%
      mutate(year = as.numeric(i_year)) 
    
    # rename interpolated model variable to indicate as model output
    model_obs_interpo <- model_obs_interpo %>% 
      rename(!!sym(paste(i_variable,"model",sep = "_")) := !!sym(i_variable))
    
    # add model subset to GLODAP
    GLODAP <- left_join(GLODAP, model_obs_interpo)
    
    # calculate annual average variable
    variable_data_tibble_annual_average <- variable_data_tibble %>%
      fselect(-month) %>%
      fgroup_by(lat, lon, depth) %>% {
        add_vars(
          fgroup_vars(., "unique"),
          fmean(., keep.group_vars = FALSE)
        )
      }
    
    # select surface annual average variable
    variable_data_tibble_annual_average_surface <- variable_data_tibble_annual_average %>%
      filter(depth == min(depth))
    
    # surface map of variable
    print(
      surface_GLODAP(
        variable_data_tibble_annual_average_surface,
        obs_depth,
        model_obs_interpo,
        i_variable
      )
    )
    # GLODAP with model subset:red point
    # GLODAP without model subset:black point
    
    # combine annual average model file together
    if (exists("annual_average_variable")) {
      annual_average_variable <-
        left_join(annual_average_variable, variable_data_tibble_annual_average)
    }
    
    if (!exists("annual_average_variable")) {
      annual_average_variable <- variable_data_tibble_annual_average
    }
    
  }
  
  # write file for annually averaged model field
  annual_average_variable %>%
    write_csv(here::here(
      "data",
      paste(i_year, "_", "annual_average_variables.csv", sep = "")
    ))
  
  rm(annual_average_variable)
  
}

# write file for GLODAP observations + subsetted model variables
GLODAP %>%
  write_csv(here::here("data",
                       "GLODAP_with_model_subset.csv"))

```
