---
title: "Observation and model variables comparison"
author: "Donghe Zhu and Dr Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r library, message = FALSE, warning = FALSE}
library(tidyverse)
library(scico)
library(gsw)
library(marelac)
```

```{r read_mask_files, include = FALSE}

basinmask <- read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "basin_mask_WOA18_AIP.csv"
  )
)

landmask <-  read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "land_mask_WOA18.csv"
  )
)

```

```{r ggplot_theme, include = FALSE}
# ggplot theme for all plots
theme_set(theme_bw())
```


# Read joined GLODAP + model data

```{r read_GLODAP_with_model_subset_data}

# set path to model analysis/subsetting output files
path_model_analysis <-
  "/net/kryo/work/loher/CESM_output/RECCAP2/analysis/"

# read file for GLODAP observations + subsetted model variables
GLODAP_model <- 
  read_csv(paste(
    paste(path_model_analysis, "glodapv2_cmorized_synthetic/", sep = ""),
    "GLODAP_with_cmorized_subset.csv",
    sep = ""
  ))

```


# Apply basin mask

```{r apply_basin_mask_to_GLODAP_model_data}

GLODAP_model <- inner_join(GLODAP_model, basinmask)

```


# Observation and model data comparison

```{r all_years_comparison}

# for loop across variables
obs_var <-
  c("tco2",
    "talk",
    "oxygen",
    "aou",
    "nitrate",
    "phosphate",
    "silicate",
    "sal",
    "tem")

model_var <-
  c(
    "dissic_model",
    "talk_model",
    "o2_model",
    "aou_model",
    "no3_model",
    "po4_model",
    "si_model",
    "so_model",
    "thetao_model"
  )

# too many figures, here instead of length(obs_var), just use the first two.
for (i in 1:9) {
  # Uncomment line below for manual testing
  # i <- 1
  
  # select correlated observation and model variable
  GLODAP_model_var <- GLODAP_model %>%
    select(year,
           month,
           lat,
           lon,
           depth,!!sym(obs_var[i]),!!sym(model_var[i])) %>%
    drop_na() %>%
    mutate(
      season = case_when(
        month %in% c(3, 4, 5) ~ "Spring",
        month %in% c(6, 7, 8) ~ "Summer",
        month %in% c(9, 10, 11) ~ "Autumn",
        month %in% c(12, 1, 2) ~ "Winter"
      )
    )
  
  # calculate equal axis limits and binwidth
  axis_lims <- GLODAP_model_var %>%
    summarise(max_value = max(c(max(!!sym(
      obs_var[i]
    )),
    max(
      !!sym(model_var[i])
    ))),
    min_value = min(c(min(!!sym(
      obs_var[i]
    )),
    min(
      !!sym(model_var[i])
    ))))
  
  binwidth_value <- (axis_lims$max_value - axis_lims$min_value) / 40
  axis_lims <- c(axis_lims$min_value, axis_lims$max_value)
  
  # obs-model plot (season)
  print(
    ggplot(GLODAP_model_var, aes(
      x = !!sym(obs_var[i]),
      y = !!sym(model_var[i])
    )) +
      geom_bin2d(binwidth = binwidth_value) +
      labs(title = "Observation (x) vs Model (y)",
           subtitle = "Seasonal comparison") +
      scale_fill_viridis_c(trans = "log10") +
      geom_abline(slope = 1,
                  col = 'red') +
      coord_equal(xlim = axis_lims,
                  ylim = axis_lims) +
      facet_wrap(~ season)
  )
  
  # obs-model plot (year)
  print(
    ggplot(GLODAP_model_var, aes(
      x = !!sym(obs_var[i]),
      y = !!sym(model_var[i])
    )) +
      geom_bin2d(binwidth = binwidth_value) +
      labs(title = "Observation (x) vs Model (y)",
           subtitle = "All years") +
      scale_fill_viridis_c(trans = "log10") +
      geom_abline(slope = 1, col = 'red') +
      coord_equal(xlim = axis_lims,
                  ylim = axis_lims)
  )
  
  
  # Calculate variable offset
  GLODAP_model_var <- GLODAP_model_var %>%
    mutate(offset = !!sym(model_var[i]) -!!sym(obs_var[i]))
  
  # Calculate annual mean offset
  GLODAP_model_var_year <- GLODAP_model_var %>%
    group_by(year) %>%
    summarise(offset = mean(offset)) %>%
    ungroup()
  
  # plot annual mean offset
  print(
    GLODAP_model_var_year %>%
      ggplot(aes(year, offset)) +
      geom_point() +
      geom_line() +
      labs(title = "Annual mean offset",
           subtitle = paste(sym(model_var[i]), "-", sym(obs_var[i])))
  )
  
  # spatial distribution of the model-observations offset for 4 depth intervals
  intervals <- c(0, 150, 500, 2000, 8000)
  for (j in 1:4) {
    # j <- 1
    GLODAP_model_var_grid <- GLODAP_model_var %>%
      filter(depth >= intervals[j],
             depth < intervals[j + 1]) %>%
      group_by(lat, lon) %>%
      summarise(offset = mean(offset)) %>%
      ungroup()
    
    # plot mean spatial distribution (model - obs)
    limit <- quantile(abs(GLODAP_model_var_grid$offset), 0.98) * c(-1, 1)
    print(
      ggplot() +
        geom_raster(data = GLODAP_model_var_grid, aes(lon, lat, fill = offset)) +
        scale_fill_scico(
          palette = "vik",
          name = "offset",
          limit = limit,
          na.value = "red"
        ) +
        coord_quickmap(expand = 0) +
        labs(
          title = paste(model_var[i],
                        "-",
                        obs_var[i],
                        " | mean offset per grid cell"),
          subtitle = paste("Depth interval:",
                           intervals[j], "-", intervals[j + 1], "m | red: outside 98th percentile"),
          x = "Longitude",
          y = "Latitude"
        ) +
        geom_raster(data = landmask,
                    aes(lon, lat), fill = "grey80")
    )
    
    print(
      GLODAP_model_var_grid %>%
        ggplot(aes(offset)) +
        geom_vline(xintercept = limit) +
        geom_histogram() +
        labs(
          title = paste(model_var[i],
                        " - ",
                        obs_var[i],
                        "mean offset per grid cell | histogram + abs. 98th Percentile"),
          subtitle = paste("Depth interval:",
                           intervals[j], "-", intervals[j + 1], "m")
        ) +
        coord_cartesian(expand = FALSE)
    )
  }
}

```

# Model diagnostics

A set of model summary statistics was calculated for each relevant variable and year.

```{r read_model_summary_stats}

# write file for model summary statistics
model_stats <-
  read_csv(paste(
    paste(path_model_analysis, "cmorized_diag/", sep = ""),
    "A_summary_stats.csv",
    sep = ""
  ))

```

```{r pivot_model_summary_stats}

model_stats_wide <- model_stats %>% 
  pivot_longer(Min.:Max.,
               names_to = "estimate",
               values_to = "value")

```

```{r GIAF_JRA_model_stats, fig.asp=7}

model_stats_wide %>% 
  ggplot(aes(year, value)) +
  geom_path() +
  geom_point() +
  facet_wrap(~ interaction(estimate, variable),
             ncol = 1,
             scales = "free_y")

```




